name: CryptoSoftInc-SBOM
description: This action builds a CycloneDX Format SBOM for a repository and sends it to an OWASP DT server

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
        shell: bash
      - run: |
          export FETCH_LICENSE=true
          npm install -g @cyclonedx/cdxgen && cdxgen -r -o bom.json
        shell: bash
      - run: |
          curl -k -X POST "${{ secrets.DT_URL }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: ${{ secrets.API_KEY }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ secrets.PROJECT_NAME }}" \
            -F "projectVersion=${{ secrets.PROJECT_VERSION }}" \
            -F "bom=@bom.json"
        shell: bash
