name: CryptoSoftInc-SBOM
description: This action builds a CycloneDX Format SBOM for a repository and sends it to an OWASP DT server

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
      
      - name: Generate SBOM
        run: |
          export FETCH_LICENSE=true
          npm install -g @cyclonedx/cdxgen
          cdxgen -r -o bom.json || { echo "❌ SBOM generation failed!"; exit 1; }
          ls -lah bom.json  # Check if SBOM file exists and print its size
          cat bom.json | head -n 20  # Print first 20 lines for debugging

      - name: Validate SBOM JSON format
        run: |
          if [ ! -s bom.json ]; then
            echo "❌ SBOM file is empty! Generation failed."
            exit 1
          fi
          jq . bom.json || { echo "❌ Invalid JSON format in SBOM!"; exit 1; }

      - name: Verify Dependency-Track Connectivity
        env:
          DT_URL: ${{ secrets.DT_URL }}
          API_KEY: ${{ secrets.DT_API_KEY }}
        run: |
          echo "Checking connection to Dependency-Track..."
          curl -v -k -X GET "$DT_URL/api/version" -H "X-Api-Key: $API_KEY"

      - name: Check if Project Exists in Dependency-Track
        env:
          DT_URL: ${{ secrets.DT_URL }}
          API_KEY: ${{ secrets.DT_API_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        run: |
          ENCODED_PROJECT_NAME=$(echo "$PROJECT_NAME" | jq -R -r @uri)
          ENCODED_PROJECT_VERSION=$(echo "$PROJECT_VERSION" | jq -R -r @uri)

          echo "Checking if project exists in Dependency-Track..."
          curl -v -k -X GET "$DT_URL/api/v1/project/lookup?name=$ENCODED_PROJECT_NAME&version=$ENCODED_PROJECT_VERSION" \
            -H "X-Api-Key: $API_KEY" -H "Accept: application/json"

      - name: Upload SBOM to Dependency-Track
        env:
          DT_URL: ${{ secrets.DT_URL }}
          API_KEY: ${{ secrets.DT_API_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        run: |
          ENCODED_PROJECT_NAME=$(echo "$PROJECT_NAME" | jq -R -r @uri)
          ENCODED_PROJECT_VERSION=$(echo "$PROJECT_VERSION" | jq -R -r @uri)

          echo "Uploading SBOM to Dependency-Track..."
          RESPONSE=$(curl -v -k -X POST "$DT_URL/api/v1/bom/upload" \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: $API_KEY" \
            --data-binary "@bom.json" -w "%{http_code}" -o response.txt)

          echo "Server Response Code: $RESPONSE"
          cat response.txt
          
          if [[ "$RESPONSE" -ne 200 && "$RESPONSE" -ne 201 ]]; then
            echo "❌ Failed to upload SBOM! Check response below:"
            cat response.txt
            exit 1
          fi
