name: CryptoSoftInc-SBOM
description: This action builds a CycloneDX Format SBOM for a repository and sends it to an OWASP DT server.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Fix Security Vulnerabilities
        run: npm audit fix --force || echo "Security vulnerabilities could not be fixed, continuing..."

      - name: Generate CycloneDX SBOM
        run: |
          export FETCH_LICENSE=true
          npm install -g @cyclonedx/cdxgen
          cdxgen -r -o bom.json || { echo "SBOM generation failed"; exit 1; }
          cat bom.json  # Output SBOM contents for debugging
          jq . bom.json || { echo "Invalid SBOM JSON"; exit 1; }

      - name: Run Markdown Linter (Non-blocking)
        run: npm run test:markdown || echo "Markdown linting failed, skipping..."

      - name: Upload SBOM to OWASP Dependency-Track
        run: |
          curl -k -X POST "${{ secrets.DT_URL }}/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: ${{ secrets.API_KEY }}" \
            -F "autoCreate=true" \
            -F "projectName=${{ secrets.PROJECT_NAME }}" \
            -F "projectVersion=${{ secrets.PROJECT_VERSION }}" \
            -F "bom=@bom.json"
