name: CryptoSoftInc-SBOM
description: This action builds a CycloneDX Format SBOM for a repository and sends it to an OWASP DT server
inputs:
  dt-url:
    description: 'The URL of the Dependency-Track API server to send the SBOM'
    required: true
  api-key:
    description: 'The API key for Dependency-Track API'
    required: true
  project-name:
    description: 'Project name'
    required: true
  project-version:
    description: 'Project version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2 
    - run: npm install
      shell: bash
    - run: |
        export FETCH_LICENSE=true
        npm install -g @cyclonedx/cdxgen
        cdxgen -r -o bom.json || { echo "SBOM generation failed"; exit 1; }
        cat bom.json  # Check file contents
        jq . bom.json || { echo "Invalid SBOM JSON"; exit 1; }
      shell: bash
    - run: |
        curl -k -X POST "${{ inputs.dt-url }}/api/v1/bom" \
          -H "Content-Type: multipart/form-data" \
          -H "X-Api-Key: ${{ inputs.api-key }}" \
          -F "autoCreate=true" \
          -F "projectName=${{ inputs.project-name }}" \
          -F "projectVersion=${{ inputs.project-version }}" \
          -F "bom=@bom.json"
      shell: bash
