name: Generate SBOM and Upload to OWASP DT

on:
  push:
    branches:
      - main  # Adjust this if needed

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: |
          export FETCH_LICENSE=true
          npm install -g @cyclonedx/cdxgen
          cdxgen -r -o bom.json
      
      - name: Log SBOM contents
        run: cat bom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact
          path: bom.json

      - name: Download SBOM Artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-artifact
          path: downloaded-sbom

      - name: Debug API Key (Masked)
        run: echo "API Key Length: ${#ODT_API_KEY}"

      - name: Validate API URL
        run: |
          echo "Validating Dependency-Track API URL..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -k -X GET "https://dt-api-tech-peat-6.org.dependencytrack.com/api/version")
          cat response.txt
          if [[ "$RESPONSE" -ne 200 ]]; then
            echo "❌ Invalid API URL or server unavailable. Check the API endpoint."
            exit 1
          fi
          echo "✅ API URL validated successfully!"
      
      - name: Upload SBOM to OWASP Dependency-Track
        env:
          ODT_API_KEY: ${{ secrets.ODT_API_KEY }}
        run: |
          echo "Uploading SBOM..."
          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -k -X POST "https://dt-api-tech-peat-6.org.dependencytrack.com/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: $ODT_API_KEY" \
            -F "autoCreate=true" \
            -F "projectName=test" \
            -F "projectVersion=1.0.0" \
            -F "bom=@downloaded-sbom/bom.json")
          
          echo "Server Response Code: $RESPONSE"
          cat response.txt
          
          if [[ "$RESPONSE" -ne 200 && "$RESPONSE" -ne 201 ]]; then
            echo "❌ Failed to upload SBOM! Check response below:"
            cat response.txt
            exit 1
          fi
          echo "✅ SBOM uploaded successfully!"
