name: Generate SBOM and Upload to OWASP DT

on:
  push:
    branches:
      - main  # Adjust this if needed

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: |
          export FETCH_LICENSE=true
          npm install -g @cyclonedx/cdxgen
          cdxgen -r -o bom.json

      - name: Log SBOM contents
        run: cat bom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact
          path: bom.json

      - name: Download SBOM Artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-artifact
          path: downloaded-sbom

      - name: Upload SBOM to OWASP Dependency-Track
        env:
          ODT_API_KEY: ${{ secrets.ODT_API_KEY }}
        run: |
          curl -k -X POST "https://dt-api-tech-peat-6.org.dependencytrack.com/api/v1/bom" \
            -H "Content-Type: multipart/form-data" \
            -H "X-Api-Key: $ODT_API_KEY" \
            -F "autoCreate=true" \
            -F "projectName=test" \
            -F "projectVersion=1.0.0" \
            -F "bom=@downloaded-sbom/bom.json"
